"""Alembic environment.

`target_metadata` is the SQLModel registry, so `--autogenerate` works. It did not
before Phase 9: `core/db.py` was raw SQL over a hand-rolled wrapper with no
metadata, and autogenerate emitted empty migrations that looked like "no changes".

The URL comes from the same settings the app uses, so there is one answer to
"which database is this?" rather than two that can disagree.
"""

from __future__ import annotations

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from pydantic_settings import BaseSettings, SettingsConfigDict  # noqa: E402
from sqlmodel import SQLModel  # noqa: E402

# Registering the table models gives --autogenerate something real to diff
# against. Before Phase 9 there was no metadata and autogenerate silently
# produced empty migrations.
import app.modules.auth.models  # noqa: E402,F401
import app.modules.rasifal.models  # noqa: E402,F401
import app.modules.report.models  # noqa: E402,F401
import app.modules.vault.models  # noqa: E402,F401
from app.core.db import DB_PATH  # noqa: E402


class _MigrationSettings(BaseSettings):
    """Only the database URL.

    Constructing the app's full `Settings` here would demand `JWT_SECRET`, which
    migrations neither have nor need — and a tool that refuses to run without an
    unrelated secret is a tool people work around.
    """

    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8", extra="ignore"
    )
    DATABASE_URL: str | None = None

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata


def _database_url() -> str:
    url = os.getenv("DATABASE_URL") or _MigrationSettings().DATABASE_URL
    if url:
        # SQLAlchemy needs the driver named; the app's psycopg2 URL may not.
        return url.replace("postgresql+psycopg://", "postgresql+psycopg2://", 1)
    return f"sqlite:///{DB_PATH}"


def run_migrations_offline() -> None:
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = _database_url()
    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # SQLite cannot ALTER most things in place; batch mode rewrites the
            # table instead. Harmless on Postgres, essential on SQLite.
            render_as_batch=True,
            # On SQLite, --autogenerate always reports TEXT vs AutoString and
            # REAL vs Float. Those are the same storage affinity, not drift, and
            # a migration built from them rewrites every table for nothing. Read
            # an autogenerated diff before committing it; columns and indexes are
            # covered by tests/modules/test_migrations.py.
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
