import { AwsClient } from "aws4fetch";

/**
 * The bucket the finished films live in.
 *
 * The renderer needs a filesystem — ffmpeg writes frames and cuts an mp4 —
 * so a day is still made on disk. What changes is where it lives afterwards:
 * the volume becomes a cache, and R2 the record, so a redeployed or replaced
 * container does not take the archive with it.
 *
 * R2 speaks S3, which means SigV4. `aws4fetch` is 80 KB and signs a `fetch`;
 * the AWS SDK is twenty times that to do the same four verbs.
 *
 * Unconfigured, every call here is a no-op and the studio behaves exactly as
 * it did before — files on the volume, nothing else.
 *
 * Server-only.
 */

const account = () => process.env.R2_ACCOUNT_ID || "";
const bucket = () => process.env.R2_BUCKET || "";

export const r2Configured = () =>
  Boolean(account() && bucket() && process.env.R2_ACCESS_KEY_ID && process.env.R2_SECRET_ACCESS_KEY);

/** One object's URL. R2's S3 endpoint is per-account, the bucket a path. */
const url = (key = "") =>
  `https://${account()}.r2.cloudflarestorage.com/${bucket()}${key ? `/${key}` : ""}`;

const client = () =>
  new AwsClient({
    accessKeyId: process.env.R2_ACCESS_KEY_ID!,
    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY!,
    service: "s3",
    // R2 has one region and calls it this.
    region: "auto",
  });

/** Everything for a day lives under one prefix, as it does on disk. */
export const keyFor = (date: string, name: string) => `rasifal-${date}/${name}`;

export async function r2Put(key: string, body: Uint8Array, contentType: string): Promise<void> {
  const res = await client().fetch(url(key), {
    method: "PUT",
    // aws4fetch types its body as the DOM's BodyInit, which in this
    // TypeScript lib does not include a plain Uint8Array.
    body: body as unknown as BodyInit,
    headers: { "Content-Type": contentType, "Content-Length": String(body.length) },
  });
  if (!res.ok) throw new Error(`r2 put ${key}: ${res.status} ${(await res.text()).slice(0, 200)}`);
}

/** The object, or null if the bucket has never heard of it. */
export async function r2Get(key: string): Promise<Buffer | null> {
  const res = await client().fetch(url(key));
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`r2 get ${key}: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

export interface R2Object {
  key: string;
  size: number;
}

/**
 * What is in the bucket under a prefix.
 *
 * ListObjectsV2, parsed out of the XML with a regex rather than a parser: the
 * response is machine-generated by S3 to a fixed shape, and a dependency to
 * read four fields of it would be the larger risk.
 */
export async function r2List(prefix: string): Promise<R2Object[]> {
  const out: R2Object[] = [];
  let token: string | undefined;

  do {
    const q = new URLSearchParams({ "list-type": "2", prefix, "max-keys": "1000" });
    if (token) q.set("continuation-token", token);
    const res = await client().fetch(`${url()}?${q}`);
    if (!res.ok) throw new Error(`r2 list ${prefix}: ${res.status}`);
    const xml = await res.text();

    for (const m of xml.matchAll(/<Contents>([\s\S]*?)<\/Contents>/g)) {
      const key = m[1].match(/<Key>([^<]+)<\/Key>/)?.[1];
      const size = Number(m[1].match(/<Size>(\d+)<\/Size>/)?.[1] ?? 0);
      if (key) out.push({ key, size });
    }
    token = /<IsTruncated>true<\/IsTruncated>/.test(xml)
      ? xml.match(/<NextContinuationToken>([^<]+)<\/NextContinuationToken>/)?.[1]
      : undefined;
  } while (token);

  return out;
}
