import type { Metadata } from "next";
import Link from "next/link";

import { CONTACT_EMAIL, LegalPage } from "@/features/marketing/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms you agree to when using Nakhatra, including what the readings are and are not.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      summary="The agreement between you and Nakhatra. The most important part is what a reading is for — please read that section even if you skip the rest."
    >
      <h2>Agreement</h2>
      <p>
        By creating an account or using Nakhatra, you agree to these terms. If you do not
        agree, please do not use the service.
      </p>

      <h2>What Nakhatra is</h2>
      <p>
        Nakhatra calculates a Vedic birth chart from the date, time and place of birth you
        provide, and uses AI to answer questions about that chart. The astronomical
        calculation is deterministic; the interpretation is generated.
      </p>

      <h2>What a reading is for</h2>
      <p>
        <strong>
          Readings are provided for personal reflection and cultural interest. They are not
          professional advice.
        </strong>
      </p>
      <ul>
        <li>
          Do not use Nakhatra in place of a doctor, therapist or pharmacist. It cannot
          diagnose, treat or predict any medical condition.
        </li>
        <li>
          Do not use it in place of a lawyer, accountant or financial adviser. It cannot
          tell you whether to make an investment, sign a contract or take a job.
        </li>
        <li>
          It does not predict deaths, lifespans or terminal illness, and it is instructed
          not to attempt to.
        </li>
        <li>
          Decisions about marriage, money, health and family are yours. Nakhatra is not
          responsible for their outcomes.
        </li>
      </ul>
      <p>
        If you are in crisis or considering harming yourself, please contact a local
        emergency service or a qualified professional. Nakhatra is not equipped to help and
        must not be relied on.
      </p>

      <h2>Accuracy</h2>
      <p>
        Chart calculations use the Swiss Ephemeris with the Lahiri ayanamsa and whole-sign
        houses. They are only as accurate as the birth details you enter —{" "}
        <strong>an incorrect birth time or place produces a wrong chart that looks
        entirely normal</strong>. Please check what you enter.
      </p>
      <p>
        Interpretations are generated by an AI model. They may be inconsistent between
        readings, and they may be wrong. Different astrologers and different classical
        texts disagree; nothing here is the single authoritative reading of your chart.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>Give accurate registration details and keep your password to yourself.</li>
        <li>You are responsible for what happens under your account.</li>
        <li>You must be 16 or older.</li>
        <li>
          If you save a chart for another person, you confirm you have their permission to
          provide their birth details.
        </li>
      </ul>

      <h2>Acceptable use</h2>
      <p>Do not:</p>
      <ul>
        <li>Resell or redistribute readings as your own professional service without a separate agreement with us.</li>
        <li>Use automated means to extract data, or attempt to bypass rate limits or authentication.</li>
        <li>Use the service to harass, defraud or frighten anyone, including making predictions about a third party in order to alarm them.</li>
        <li>Attempt to disrupt the service or access accounts that are not yours.</li>
      </ul>
      <p>We may suspend accounts that break these rules.</p>

      <h2>Availability</h2>
      <p>
        We aim to keep Nakhatra available but do not guarantee uninterrupted service.
        Features may change or be withdrawn. Where a reading depends on a third-party AI
        provider, an outage there may make readings temporarily unavailable.
      </p>

      <h2>Content and ownership</h2>
      <p>
        Your birth details and your questions remain yours. Readings generated for you are
        yours to keep and use personally. The software, design, name and mark of Nakhatra
        remain ours.
      </p>
      <p>
        You grant us the limited permission needed to run the service — to store your data,
        and to transmit it to the providers listed in our{" "}
        <a href="/privacy">Privacy Policy</a> in order to produce a reading.
      </p>

      <h2>Our social media channels</h2>
      <p>
        We publish the day&apos;s rasifal as short videos on channels we own — TikTok and
        YouTube today, others perhaps later. Those videos are ours, and the same rules
        apply to them as to anything else here: the rasifal in them is general and
        computed for a sign rather than for a person, and it is not advice on your health,
        money, marriage or legal position. Read them the way you would read the{" "}
        <Link href="/rasifal">rasifal page</Link> — see <em>What a reading is for</em> above.
      </p>
      <p>
        Watching, following or commenting on those channels is a matter between you and
        the platform, under its terms, not ours. Nothing you do there gives you an account
        with us, and nothing you do here is posted there.
      </p>

      <h2>Payment</h2>
      <p>
        Nakhatra is currently free to use. If we introduce paid features we will set out
        the price and terms before you are charged, and using a paid feature will be your
        choice.
      </p>

      <h2>Liability</h2>
      <p>
        The service is provided &ldquo;as is&rdquo;. To the extent permitted by law, we are
        not liable for indirect or consequential loss, or for decisions you make based on a
        reading. Nothing in these terms limits liability that cannot be limited by law.
      </p>

      <h2>Ending your use</h2>
      <p>
        You may stop using Nakhatra and ask us to delete your account at any time by
        emailing <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. We may suspend or
        close an account that breaches these terms.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of Nepal, and the courts of Nepal have
        jurisdiction over any dispute.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms and will revise the date at the top. Continued use after
        a change means you accept the updated terms; material changes will be notified
        before they take effect.
      </p>
    </LegalPage>
  );
}
